import '../styles/globals.css'
import Head from 'next/head'
import Script from 'next/script'

function MyApp({ Component, pageProps }) {
  return <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta charSet="UTF-8" />

        <title>nirvana</title>

        <link rel="icon" href="/icon.png" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Satisfy&display=swap"
          rel="stylesheet"
        />

        <link
          href="https://fonts.googleapis.com/css2?family=Baloo+Bhaijaan+2&display=swap"
          rel="stylesheet"
        />

        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" />
        <link href="/assets/plugins/global/plugins.bundle.css" rel="stylesheet" type="text/css" />
        <link href="/assets/css/style.bundle.css" rel="stylesheet" type="text/css" />
      </Head>

      <body>
        <Component {...pageProps} />
        
        <Script type="text/javascript" defer src="/assets/plugins/global/plugins.bundle.js"></Script>
        <Script type="text/javascript" defer  src="/assets/js/scripts.bundle.js"></Script>
      </body>
      
  </>
}

export default MyApp
